### ISSUE TITLE
CMD DEMO NEEDED?

### ISSUE THREAD

**Issue by dunk8888** [Entropy512/I2C_RGB#1]
HOW DO I SEND COMMANDS TO THE BOARD? CAN YOU SHOW EXAMPLE OF WHAT TO RIGHT IN THE CMD WINDOW? I TAKE IT ITS SOMTHING LIKE 32,225,225,000
32 FOR ADDRESS AND THE NEXT THREE BYTS FOR COLORS? AM I CLOSE?

**Comment by Entropy512** [comment]
This is only an I2C device.  How to send data to an I2C bus is up to you.  Bus Pirate is one option, I forget what I used years ago when I last touched this product.

For 99% of users, a WS2811/2812 is sufficient, cheaper, and easier to use, which is why this project is currently dead.
